# Generated by Django 6.1 on 2026-08-17 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('tenants', '0002_hospital_last_mrn_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Internal test code, e.g. CBC', max_length=30)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('sputum', 'Sputum'), ('swab', 'Swab'), ('tissue', 'Tissue'), ('other', 'Other')], default='blood', max_length=20)),
                ('unit', models.CharField(blank=True, help_text='e.g. mg/dL, x10^9/L', max_length=50)),
                ('reference_range', models.CharField(blank=True, help_text='e.g. 4.5–11.0 x10^9/L', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sample_status', models.CharField(choices=[('pending', 'Pending Collection'), ('collected', 'Sample Collected'), ('result_entered', 'Result Entered')], default='pending', max_length=20)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('result_value', models.CharField(blank=True, max_length=200)),
                ('result_notes', models.TextField(blank=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('result_entered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.hospital')),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_result', to='clinical.laborder')),
                ('result_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample_collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='lab.labtest')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='unique_lab_test_per_hospital'),
        ),
    ]
