# Generated by Django 6.1 on 2026-08-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='last_mrn_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
