# Generated by Django 6.1 on 2026-08-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_hospital_last_mrn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='last_invoice_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
