# Generated by Django 6.1 on 2026-08-17 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('tenants', '0002_hospital_last_mrn_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('history_notes', models.TextField(blank=True)),
                ('examination_notes', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('icd10_code', models.CharField(blank=True, max_length=10, verbose_name='ICD-10 code')),
                ('advice', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('test_name', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='clinical.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.hospital')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, help_text='e.g. 500mg', max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='e.g. 1-0-1 (morning-noon-night)', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='e.g. 5 days', max_length=100)),
                ('instructions', models.CharField(blank=True, help_text='e.g. after meals', max_length=255)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='clinical.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.hospital')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pulse_rate', models.PositiveSmallIntegerField(blank=True, help_text='beats per minute', null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, help_text='breaths per minute', null=True)),
                ('spo2_percent', models.PositiveSmallIntegerField(blank=True, help_text='Oxygen saturation %', null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.hospital')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
