# Generated by Django 6.1 on 2026-08-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit dispensed', max_digits=10),
        ),
    ]
